实验6：异常

异常的体系：

Throwable    错误类或者异常的超类

Error  错误   错误一般是用于jvm或者是硬件引发的问题，所以我们一般不会通过代码去处理错误的。 仅靠程序无法修复的重量级异常

Exception 异常   是需要通过代码去处理的。

RuntimeExcption 异常(运行时异常)通常有以下几种：

- 错误的类型转换
- 数组访问越界
- 访问 null 指针
- 算术异常

在Java中采用5个关键字来处理异常：

（1）     try 尝试执行的代码块

（2）     catch 用来捕获异常对象的代码块

（3）     throw 方法体内用于抛出异常对象

（4）     throws 用来声明方法可能会出现的异常

throw和throws的区别：

throws表示出现异常的一种可能性，并不一定会发生这些异常；throw则是抛出了异常，执行throw则一定抛出了某种异常对象。

```
import java.io.FileInputStream;
import java.io.FileNotFoundException;

public class MultipleCapturesDemo {
    public static void main(String[] args) {
        try {
            new FileInputStream("");
        } catch (FileNotFoundException e) {
            System.out.println("IO 异常");
        } catch (Exception e) {
            System.out.println("发生异常");
        }
    }
}
```

![1559140056442](C:\Users\admin\AppData\Roaming\Typora\typora-user-images\1559140056442.png)

```
public class CatchException {
    public static void main(String[] args) {
        try {
            System.out.println("I am try block.");
            Class<?> tempClass = Class.forName("");           
            System.out.println("Bye! Try block.");

        } catch (ClassNotFoundException e) {
        
            System.out.println("I am catch block.");
            e.printStackTrace();
            System.out.println("Goodbye! Catch block.");

        } finally {
            System.out.println("I am finally block.");
        }
    }
}
```

![1559141182288](C:\Users\admin\AppData\Roaming\Typora\typora-user-images\1559141182288.png)

